// <auto-generated />
using System;
using HomeworkAspItstepAngular.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeworkAspItstepAngular.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.15");

            modelBuilder.Entity("HomeworkAspItstepAngular.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("ApplicationUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ApplicationUserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HomeworkAspItstepAngular.Entities.Note", b =>
                {
                    b.Property<Guid>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NotepadId")
                        .HasColumnType("TEXT");

                    b.HasKey("NoteId");

                    b.HasIndex("NotepadId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("HomeworkAspItstepAngular.Entities.Notepad", b =>
                {
                    b.Property<Guid>("NotepadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotepadName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NotepadId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Notepads");
                });

            modelBuilder.Entity("HomeworkAspItstepAngular.Entities.Note", b =>
                {
                    b.HasOne("HomeworkAspItstepAngular.Entities.Notepad", null)
                        .WithMany("Notes")
                        .HasForeignKey("NotepadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeworkAspItstepAngular.Entities.Notepad", b =>
                {
                    b.HasOne("HomeworkAspItstepAngular.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("Notepads")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("HomeworkAspItstepAngular.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Notepads");
                });

            modelBuilder.Entity("HomeworkAspItstepAngular.Entities.Notepad", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
